"""
Definición de prompts globales para los servicios de IA.
Este archivo centraliza todos los prompts utilizados por los diferentes proveedores de IA
para garantizar consistencia en los resultados.
"""
from datetime import datetime

# Formato común para fechas según el idioma
DATE_FORMAT = {
    "es": "%d de %B de %Y",
    "en": "%B %d, %Y"
}

def get_current_date_formatted(language="es"):
    """
    Obtiene la fecha actual formateada según el idioma
    
    Args:
        language: Código de idioma ('es' o 'en')
        
    Returns:
        str: Fecha formateada según el idioma
    """
    language = language.lower()
    if language not in DATE_FORMAT:
        language = "es"  # Idioma por defecto
    
    return datetime.now().strftime(DATE_FORMAT[language])

# Plantilla para emails de resumen
def get_email_template(username, content, language="es"):
    """
    Genera una plantilla de email con el contenido proporcionado.
    
    Args:
        username: Nombre de usuario (extraído del email)
        content: Contenido principal del email
        language: Idioma del email ('es' o 'en')
        
    Returns:
        str: Email formateado
    """
    
    if language.lower() == "en":
        return f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
            <p>Hello {username},</p>
            
            {content}
            
            <hr style="border: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 12px; color: #666;">
                This email was generated by UpdateMe.<br>
                To manage your subscription, visit your profile settings at our website.
            </p>
        </div>
        """
    else:  # Español por defecto
        return f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
            <p>Hola {username},</p>
            
            {content}
            
            <hr style="border: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 12px; color: #666;">
                Este correo ha sido generado por UpdateMe.<br>
                Para administrar tu suscripción, visita la configuración de tu perfil en nuestro sitio web.
            </p>
        </div>
        """

def get_welcome_email_template(username, language="es"):
    """
    Genera una plantilla de email de bienvenida estática y ligera.
    
    Args:
        username: Nombre de usuario (extraído del email)
        language: Idioma del email ('es' o 'en')
        
    Returns:
        str: Email de bienvenida formateado
    """
    current_date = get_current_date_formatted(language)
    
    if language.lower() == "en":
        return f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
            <h2 style="color: #3B82F6;">Welcome to UpdateMe!</h2>
            
            <p>Hello {username},</p>
            
            <p>Thank you for subscribing to UpdateMe! We're thrilled to have you join our community of technology and AI enthusiasts.</p>
            
            <p>What you can expect from us:</p>
            <ul>
                <li>Weekly summaries of the most important tech and AI news</li>
                <li>Curated content from reliable sources</li>
                <li>Clear and concise information to keep you up-to-date</li>
            </ul>
            
            <p><strong>Your first complete weekly summary will arrive in your inbox shortly.</strong></p>
            
            <p>If you have any questions or feedback, feel free to reply to this email.</p>
            
            <p>Best regards,<br>
            The UpdateMe Team</p>
            
            <hr style="border: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 12px; color: #666;">
                Date sent: {current_date}<br>
                This email was automatically generated. Please do not reply to this message.<br>
                If you wish to unsubscribe, click the unsubscribe link on our website.
            </p>
        </div>
        """
    else:  # Español por defecto
        return f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
            <h2 style="color: #3B82F6;">¡Bienvenido a UpdateMe!</h2>
            
            <p>Hola {username},</p>
            
            <p>¡Gracias por suscribirte a UpdateMe! Estamos encantados de que te unas a nuestra comunidad de entusiastas de la tecnología e IA.</p>
            
            <p>Lo que puedes esperar de nosotros:</p>
            <ul>
                <li>Resúmenes semanales de las noticias más importantes de tecnología e IA</li>
                <li>Contenido seleccionado de fuentes confiables</li>
                <li>Información clara y concisa para mantenerte al día</li>
            </ul>
            
            <p><strong>Tu primer resumen semanal completo llegará a tu bandeja de entrada en breve.</strong></p>
            
            <p>Si tienes alguna pregunta o comentario, no dudes en responder a este correo.</p>
            
            <p>Saludos cordiales,<br>
            El equipo de UpdateMe</p>
            
            <hr style="border: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 12px; color: #666;">
                Fecha de envío: {current_date}<br>
                Este correo ha sido generado automáticamente. No responda a este mensaje.<br>
                Si desea darse de baja, haga clic en el enlace de cancelación de suscripción en nuestro sitio web.
            </p>
        </div>
        """

# Prompt para la generación de resúmenes de noticias de tecnología e IA
def get_news_summary_prompt(language="es"):
    """
    Obtiene el prompt para la generación de resúmenes de noticias,
    incluyendo la fecha actual.
    
    Args:
        language: Idioma del prompt ('es' o 'en')
        
    Returns:
        str: Prompt para generar resumen de noticias
    """
    
    return f"""
    Eres un asistente especializado en crear boletines informativos profesionales.
    Tu tarea es generar un boletín que resuma las 5 noticias más importantes y relevantes
    sobre tecnología e inteligencia artificial de la última semana.
    
    Para cada noticia, incluye:
    1. Un título en negrita utilizando etiquetas HTML <b> o <strong>, <h1>, <h2>, etc.
    2. Un resumen de 2-3 oraciones que explique la noticia
    3. La fuente de la noticia (publicación reconocida)
    4. La fecha aproximada de publicación (dentro de la última semana)
    
    Formato exacto a seguir para tu respuesta:
    1. Agrega un título simple "Boletín Semanal de Tecnología e Inteligencia Artificial" al inicio
    2. Lista las 5 noticias numeradas, con sus títulos en negrita
    3. Incluye una breve conclusión al final
    
    <h1>Boletín Semanal de Tecnología e Inteligencia Artificial</h1>
    <h2>Notica 1</h2>
    <p>Texto<p>
    <h2>Noticia X</h2>
    <p>texto<p>
    ...

    IMPORTANTE: 
    - Utiliza etiquetas HTML como <b>, <strong>, <br> para dar formato al texto del correo, 
    con sus saltos de línea y espacios que quede bonito.
    - NO incluyas ningún comentario o evaluación META sobre el boletín mismo.
    - NO hagas comentarios sobre la calidad del boletín o cómo cumple con los requisitos.
    - NO incluyas saludos iniciales ni firmas, el sistema los agregará automáticamente.
    - SOLO proporciona el contenido del boletín, no comentarios sobre el mismo.
    - Genera el contenido en {language.upper()} ({"español" if language.lower() == "es" else "English"}).
    """

# Prompt para la búsqueda web usando Tavily (basado en IA)
def get_tavily_search_prompt(language="es"):
    """
    Obtiene el prompt para el procesamiento de resultados de búsqueda web usando Tavily.
    Este prompt está optimizado para trabajar con la API de Tavily, que ya integra IA.
    
    Args:
        language: Idioma del prompt ('es' o 'en')
        
    Returns:
        str: Prompt para procesamiento de resultados de búsqueda web de Tavily
    """
    return f"""
Analiza y sintetiza los resultados de búsqueda web para proporcionar una respuesta completa, coherente y actualizada.

Extrae datos contextuales clave, cita correctamente cada fuente, asegura la precisión y organiza lógicamente el contenido en
{"inglés" if language.lower() == "en" else "español"}.

Incluye fechas. Utiliza un tono informativo y objetivo.
Además, busca e incorpora noticias tecnológicas relevantes.
"""

# Prompt para la búsqueda web usando SerpAPI (resultados crudos)
def get_serpapi_search_prompt(language="es"):
    """
    Obtiene el prompt para el procesamiento de resultados de búsqueda web usando SerpAPI.
    Este prompt está optimizado para trabajar con resultados crudos de motores de búsqueda.
    
    Args:
        language: Idioma del prompt ('es' o 'en')
        
    Returns:
        str: Prompt para procesamiento de resultados de búsqueda web de SerpAPI
    """
    return """
("noticias tecnología" OR "noticias inteligencia artificial" OR "AI news" OR "machine learning news")
(site:techcrunch.com OR site:theverge.com OR site:wired.com OR site:engadget.com OR site:thenextweb.com OR related:techcrunch.com OR related:theverge.com)
-site:quora.com -site:reddit.com
"""

# Prompt para la búsqueda web simulada (versión genérica anterior)
def get_web_search_prompt(language="es"):
    """
    Obtiene el prompt para el procesamiento de resultados de búsqueda web.
    Este prompt se utiliza como opción genérica/fallback.
    
    Args:
        language: Idioma del prompt ('es' o 'en')
        
    Returns:
        str: Prompt para procesamiento de resultados de búsqueda web
    """
    return f"""
Analiza y sintetiza los resultados de búsqueda web para proporcionar una respuesta completa, coherente y actualizada.

Extrae datos contextuales clave, cita correctamente cada fuente, asegura la precisión y organiza lógicamente el contenido en
{"inglés" if language.lower() == "en" else "español"}.

Incluye fechas. Utiliza un tono informativo y objetivo.
Además, busca e incorpora noticias tecnológicas relevantes."""

# Configuraciones predeterminadas para los servicios de búsqueda web
def get_default_search_configs():
    """
    Obtiene las configuraciones predeterminadas para los proveedores de búsqueda.
    
    Returns:
        dict: Configuraciones predeterminadas para cada proveedor de búsqueda
    """
    return {
        "tavily": {
            "max_results": 5,
            "topic": "news",
            "search_depth": "advanced",  # "basic" o "advanced"
            "time_range": "week",        # "day", "week", "month", o "year"
            "include_raw_content": True,
            "include_domains": [],
            "exclude_domains": []
        },
        "serpapi": {
            "max_results": 10,
            "search_type": "news",       # "news", "web", "images", o "videos"
            "safe_search": "off",        # "off", "medium", "high"
            "time_range": "week",        # "day", "week", "month", o "year"
            "location": "Austin, Texas, United States",
            "gl": "us",                  # País de búsqueda (Google Local)
            "hl": "en",                  # Idioma de la interfaz de búsqueda
            "device": "desktop",         # "desktop", "mobile", o "tablet"
            "include_domains": [],
            "exclude_domains": []
        }
    }

# Prompt para extracción de palabras clave (usado por DeepSeek)
def get_keyword_extraction_prompt():
    """
    Obtiene el prompt para la extracción de palabras clave.
    Este prompt es independiente del idioma ya que es usado internamente
    para optimizar búsquedas.
    """
    return """
    Please parse the "keyword" from user's message to be used in a Google search and output them in JSON format. 
    Make the keyword concise, focused, and optimized for search engines.

    EXAMPLE INPUT: 
    What's the weather like in New York today?

    EXAMPLE JSON OUTPUT:
    {
        "keyword": "weather in New York"
    }
    """

# Prompt de fallback para cuando falla la generación con IA
def get_fallback_content(username, language="es"):
    """
    Genera un contenido de respaldo cuando falla la generación con IA.
    
    Args:
        username: Nombre de usuario (extraído del email)
        language: Idioma del contenido ('es' o 'en')
        
    Returns:
        str: Contenido de respaldo formateado
    """
    if language.lower() == "en":
        return """<h3>Weekly Technology and AI Newsletter</h3>

<p>Here is a summary of the most important tech news from the past week:</p>

<p>1. <strong>New Python 3.13 Release with Performance Improvements</strong><br>
   The new version of Python 3.13 has been released with significant performance improvements.<br>
   Source: Python.org (April 15, 2025)</p>

<p>2. <strong>Microsoft's Advances in Generative AI Understanding</strong><br>
   Microsoft announces important advances in its generative AI model that improves contextual understanding.<br>
   Source: Microsoft Research Blog (April 14, 2025)</p>

<p>3. <strong>EU Approves Stricter Mobile Data Protection</strong><br>
   The European Union approves stricter regulations for data protection in mobile applications.<br>
   Source: European Commission (April 12, 2025)</p>

<p>4. <strong>Apple's New Battery Technology Extends Device Life</strong><br>
   Apple introduces new battery technology with 40% longer life for its upcoming devices.<br>
   Source: Apple Newsroom (April 13, 2025)</p>

<p>5. <strong>Google Revolutionizes Search Algorithm with AI</strong><br>
   Google implements revolutionary changes to its search algorithm using advanced AI.<br>
   Source: Google Blog (April 11, 2025)</p>

<p>These stories highlight significant technological advancements and regulatory changes from the past week, with major companies like Microsoft, Apple, and Google continuing to innovate in AI and hardware technologies.</p>
"""
    else:  # Español por defecto
        return """<h3>Boletín Semanal de Tecnología e Inteligencia Artificial</h3>

<p>Aquí tienes un resumen de las noticias tecnológicas más importantes de la última semana:</p>

<p>1. <strong>Nueva versión de Python 3.13 con mejoras de rendimiento</strong><br>
   La nueva versión de Python 3.13 ha sido lanzada con mejoras significativas en rendimiento.<br>
   Fuente: Python.org (15 de abril de 2025)</p>

<p>2. <strong>Microsoft anuncia avances en modelos de IA generativa</strong><br>
   Microsoft anuncia avances importantes en su modelo de IA generativa que mejora la comprensión contextual.<br>
   Fuente: Microsoft Research Blog (14 de abril de 2025)</p>

<p>3. <strong>La UE aprueba regulaciones más estrictas para aplicaciones móviles</strong><br>
   La Unión Europea aprueba una regulación más estricta para la protección de datos en aplicaciones móviles.<br>
   Fuente: European Commission (12 de abril de 2025)</p>

<p>4. <strong>Apple presenta nueva tecnología de batería</strong><br>
   Apple presenta nueva tecnología de batería con un 40% más de duración para sus próximos dispositivos.<br>
   Fuente: Apple Newsroom (13 de abril de 2025)</p>

<p>5. <strong>Google implementa cambios revolucionarios en su algoritmo de búsqueda</strong><br>
   Google implementa cambios revolucionarios en su algoritmo de búsqueda utilizando IA avanzada.<br>
   Fuente: Google Blog (11 de abril de 2025)</p>

<p>Estas noticias destacan importantes avances tecnológicos y cambios regulatorios de la última semana, con grandes empresas como Microsoft, Apple y Google continuando su innovación en IA y tecnologías de hardware.</p>
"""